config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gorbayhub.urls')),
]

handler404 = "gorbayhub.views.page_not_found_view"

gorbayhub/urls.py
from django.urls import path, include
from . import views
app_name = 'gorbayhub'

urlpatterns = [
    path('', views.home, name='Home'),
    path('Add/', views.add, name='Add'),
    path('Save', views.save, name='Save'),
    path('Post/<slug:slug>', views.post, name='Post'),
]

gorbayhub/models.py
from django.db import models

# Create your models here.

class Roman(models.Model):
	titel = models.CharField(max_length=200, verbose_name='عنوان')
	body = models.TextField(verbose_name='رمان')

	def __str__(self):
		return self.titel

class Roman2(models.Model):
	name = models.CharField(max_length=200, verbose_name= 'نویسنده')
	titel = models.CharField(max_length=200, verbose_name='عنوان')
	slug = models.SlugField(max_length=200, unique=True,verbose_name='نشانی')
	body = models.TextField(verbose_name='رمان')
	view = models.BigIntegerField(verbose_name='بازدید')
	admin = models.CharField(max_length=200, verbose_name= 'ادمین')

	

	class Meta:
		verbose_name = "رمان"
		verbose_name_plural = 'رمان ها'
	def __str__(self):
		return f"{self.titel}-{self.view}-{self.admin}"

class Roman3(models.Model):
	name = models.CharField(max_length=200, verbose_name= 'نویسنده')
	titel = models.CharField(max_length=200, verbose_name='عنوان')
	slug = models.SlugField(max_length=200, unique=True,verbose_name='نشانی')
	body = models.TextField(verbose_name='رمان')
	view = models.BigIntegerField(verbose_name='بازدید')
	admin = models.CharField(max_length=200, verbose_name= 'ادمین')

	

	class Meta:
		verbose_name = "رمان"
		verbose_name_plural = 'رمان ها'
	def __str__(self):
		return f"{self.name}-{self.titel}-{self.view}-{self.admin}"

gorbayhub/views.py
from django.shortcuts import render
from random import choice
from .models import Roman3
# Create your views here.

def _tmpGeneration():
	tmp_session = ""
	choices = [*"abcdefghijklmnopqrstuvwxyz"]
	for i in range(32): tmp_session += choice(choices)
	return tmp_session

def home(request):
	context = {
		"roman":Roman3.objects.all().order_by('-view')
	}
	return render(request, 'gorbayhub/home.html', context)

def add(request):
	return render(request, 'gorbayhub/add.html')


def save(request):
	name = request.POST['name']
	titel = request.POST['titel']
	body = request.POST['body']
	slug = _tmpGeneration()
	view = 0
	admin = "N"
	res = Roman3(name=name, titel=titel, slug=slug, body=body, view=view, admin=admin)
	res.save()
	return render(request, 'gorbayhub/save.html')

def post(request, slug):
	post = Roman3.objects.get(slug=slug)
	post.view += 1
	post.save()
	context = {
		"post":Roman3.objects.get(slug=slug)
	}
	return render(request, 'gorbayhub/post.html', context)	

def page_not_found_view(request,exception):
	return render(request, 'gorbayhub/404.html', status=404)

gorbayhub/templates/gorbayhub/add.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>گوربای هاب | اضافه کردن رمان</title>
	<link rel="stylesheet" type="text/css" href="{% static 'gorbayhub/style.css' %}">
</head>
<body style="display: grid;place-items: center;">
	<nav class="tabs" style="margin-bottom: 50px;">
		<h1 class="h1">🐈 گوربای هاب جایی برای افراد اهل دل</h1>
	</nav>
    <div>
    	<form style="background: #ffffff;display: grid;place-items: center;justify-items: center;justify-content: center;align-items: center;border-radius: 10px;box-shadow: 0px 0px 1px 1px rgba(0,0,0,0.2);margin-bottom: 10px;" method="POST" action="{% url 'gorbayhub:Save' %}">
			{% csrf_token %}
	        <input type="text" placeholder="نام نویسنده" name="name" style="padding: 5px;direction: rtl;font-size: x-large;border-radius: 8px;margin-top: 10px;">
	        <input type="text" placeholder="عنوان رمان" name="titel" style="padding: 5px;direction: rtl;font-size: x-large;border-radius: 8px;margin-top: 10px;">
	        <textarea type="text" placeholder="متن رمان" name="body" style="padding: 5px;direction: rtl;font-size: x-large;border-radius: 8px;margin: 10px;width: 600px; height: 900px;"></textarea>
	        <button class="btn" style="margin-bottom: 10px;">ارسال</button> 
	    </form>
    </div>
		
</body>
</html>

gorbayhub/templates/gorbayhub/home.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>گوربای هاب | Gorbay Hub</title>
	<link rel="stylesheet" type="text/css" href="{% static 'gorbayhub/style.css' %}">
</head>
<body>
	<nav class="tabs">
		<h1 class="h1">🐈 گوربای هاب جایی برای افراد اهل دل</h1>
		<a class="a" href="{% url 'gorbayhub:Add' %}">اضافه کردن رمان خودتان</a>
	</nav>
	<h1 class="h_1">تازه ترین رمان ها</h1>
	{% for i in roman %}
	{% if i.admin == "Y" %}
		<div class="roman">
			<img class="img"src="{% static 'gorbayhub/main-photo.svg' %}" alt="img">
				<div class="comment-box__body" style="margin-right: 10px;">
					<a href="Post/{{i.slug}}" style="text-decoration: none;" class="comment-box__details"><span>{{i.name}}</span><span class="comment-box__details-date"><img src="{% static 'gorbayhub/3-1.png' %}" style="width: 15px;height: 15px;margin-right: 5px;" alt="icon"></span></a>
					<h3 class="h3"> {{i.titel}} | <span>👁 {{i.view}}</span></h3>
				</div>
			</div>
	{% else %}
			<div class="roman">
			<img class="img"src="{% static 'gorbayhub/main-photo.svg' %}" alt="img">
				<div class="comment-box__body" style="margin-right: 10px;">
					<a href="Post/{{i.slug}}" style="text-decoration: none;" class="comment-box__details"><span>{{i.name}}</span><span class="comment-box__details-date"></span></a>
					<h3 class="h3"> {{i.titel}} | <span>👁 {{i.view}}</span></h3>
				</div>
			</div>.
	{% endif %}
	{% endfor %}
</body>
</html>

gorbayhub/templates/gorbayhub/post.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>گوربای هاب | {{post.titel}}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'gorbayhub/style.css' %}">
</head>
<body>
	<nav class="tabs">
		<h1 class="h1">🐈 گوربای هاب جایی برای افراد اهل دل</h1>
	</nav>
    <p></p>
    <div style="display: grid;place-items: center;justify-items: center;justify-content: center;align-items: center;">
        {% if post.admin == "Y" %}
            <div class="best">
                <div class="pr">
                    <img class="img"src="{% static 'gorbayhub/main-photo.svg' %}" alt="img">
                    <div class="comment-box__body" style="margin-right: 10px;">
                        <h2 class="comment-box__details"><span>{{post.name}}</span><span class="comment-box__details-date"><img src="{% static 'gorbayhub/3-1.png' %}" style="width: 15px;height: 15px;margin-right: 5px;" alt="icon"></span></h2>
                        <h3 class="h3"> {{post.titel}} | <span>👁 {{post.view}}</span></h3>
                    </div>  
                </div>
                <hr>
                <div style="direction: rtl;margin-left: 10px;margin-right: 10px;font-family: ISDN;width: 650px;">
                    <p style="font-family: ISDN;">{{post.body|linebreaks}}</p>
                </div> 
            </div> 
        {% else %}
            <div class="best">
                <div class="pr">
                    <img class="img"src="{% static 'gorbayhub/main-photo.svg' %}" alt="img">
                    <div class="comment-box__body" style="margin-right: 10px;">
                        <h2 class="comment-box__details"><span>{{post.name}}</span><span class="comment-box__details-date"></span></h2>
                        <h3 class="h3"> {{post.titel}} | <span>👁 {{post.view}}</span></h3>
                    </div>  
                </div>
                <hr>
                <div style="direction: rtl;margin-left: 10px;margin-right: 10px;font-family: ISDN;width: 650px;">
                    <p style="font-family: ISDN;">{{post.body|linebreaks}}</p>
        {% endif %}
    </div>
	
		
</body>
</html>

gorbayhub/templates/gorbayhub/save.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>گوربای هاب | با موفقیت ذخیره شد</title>
	<link rel="stylesheet" type="text/css" href="{% static 'gorbayhub/style.css' %}">
</head>
<body style="display: grid;place-items: center;">
	<nav class="tabs" style="margin-bottom: 100px;">
		<h1 class="h1">🐈 گوربای هاب جایی برای افراد اهل دل</h1>
	</nav>
	<form method="GET" action="{% url 'gorbayhub:Home' %}">
    <div class="cof">
        <h1 class="h_1" style="color: rgb(0, 197, 0);">رمان با موفقیت ثبت شد</h1>
        <button class="btn">بازگشت به صفحه اصلی</button>
    </div>
		
</body>
</html>
